# Generated by Django 5.1.2 on 2024-11-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job1', models.CharField(max_length=200)),
                ('job2', models.CharField(max_length=200)),
                ('job3', models.CharField(max_length=200)),
                ('job4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_submitted', models.DateTimeField(verbose_name='date submitted')),
                ('jobs_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.jobs')),
            ],
        ),
    ]
