# Generated by Django 5.1.2 on 2024-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_user_jobs_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs_offered',
        ),
        migrations.AddField(
            model_name='user',
            name='jobs_offered',
            field=models.ManyToManyField(to='polls.jobs'),
        ),
    ]
